name: google_language_fonts
description: A package to include languages with fonts from fonts.google.com in your Flutter app.
version: 2.0.0-nullsafety.0
repository: https://github.com/mzdm/google-language-fonts-flutter

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ^1.17.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0-nullsafety.0
  path_provider: ^2.0.0-nullsafety
  crypto: ^3.0.0-nullsafety.0
  meta: ^1.3.0-nullsafety.6
  equatable: ^2.0.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3
  mockito: ^5.0.0-nullsafety.7
  mustache: ^1.1.1
  protobuf: ^2.0.0-nullsafety.1
  protoc_plugin: ^20.0.0-nullsafety.1
  console: ^3.1.0
